openapi: 3.0.0
info:
  title: Purchases API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8888/purchases
    description: Optional server description, e.g. Main (production) server
paths:
  /purchasesList:
    get:
      summary: Returns a list of purchases.
      tags:
        - Purchase
      description: Optional extended description in CommonMark or HTML.
      operationId: getPurchases
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Purchase"
# MODEL ----------------------------------------------------------------

components:
  schemas:
    Purchase:
      type: object
      properties:
        id:
          type: integer
        createdDate:
          type: string
          format: date-time
        checked:
          type: boolean
        checkedDate:
          type: string
          format: date-time
        name:
          type: string
        text:
          type: string
        username:
          type: string
        shared:
          type: boolean
        sharedForUsername:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/PurchaseItem"
    PurchaseItem:
      type: object
      properties:
        id:
          type: integer
        checked:
          type: boolean
        checkedDate:
          type: string
          format: date-time
        itemName:
          type: string
        itemDescription:
          type: string
