openapi: 3.0.0
info:
  title: Purchases API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8888/purchases
    description: Optional server description, e.g. Main (production) server
paths:
  /purchase:
    get:
      tags:
        - Purchase
      operationId: getPurchases
      summary: "Get list of all Purchases"
      responses:
        '200':
          description: "Retrieved list of all Purchases"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Purchase"
    post:
      tags:
        - Purchase
      operationId: createPurchase
      summary: "Creates new Purchase"
      requestBody:
        description: "Purchase"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Purchase"
      responses:
        '200':
          description: "Created Purchase"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Purchase"
    put:
      tags:
        - Purchase
      operationId: editPurchase
      summary: "Edits Purchase"
      requestBody:
        description: "Purchase"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Purchase"
      responses:
        '200':
          description: "Edited Purchase"
  /purchase/{purchaseId}:
    get:
      tags:
        - Purchase
      operationId: getPurchaseById
      summary: "Get Purchase by id"
      parameters:
        - in: path
          required: true
          name: purchaseId
          description: "Id of the Purchase"
          schema:
            type: integer
      responses:
        '200':
          description: "Retrieved Purchase"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Purchase"
    delete:
      tags:
        - Purchase
      operationId: deletePurchase
      summary: "Deletes existing Purchase"
      parameters:
        - in: path
          required: true
          name: purchaseId
          description: "Id of the Purchase"
          schema:
            type: integer
      responses:
        '200':
          description: "Deleted Purchase"



# MODEL ----------------------------------------------------------------
components:
  schemas:
    Purchase:
      type: object
      properties:
        id:
          type: integer
        createdDate:
          type: string
          format: date-time
        checked:
          type: boolean
        checkedDate:
          type: string
          format: date-time
        name:
          type: string
        text:
          type: string
        username:
          type: string
        shared:
          type: boolean
        sharedForUsername:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/PurchaseItem"
    PurchaseItem:
      type: object
      properties:
        id:
          type: integer
        purchaseId:
          type: integer
        checked:
          type: boolean
        checkedDate:
          type: string
          format: date-time
        itemName:
          type: string
        itemDescription:
          type: string
